#!/bin/sh

# This script is based on Nordic's `env.sh`, generated by the toolchain installer. Instead of
# sourcing that script, we reduce the exports to a minimum via this setup script.

shell_name=$(basename "$SHELL")

export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk-0.17.2
source $HOME/zephyrproject/zephyr/zephyr-env.sh
west zephyr-export
